### PR TITLE
Enable Eslint

### PR DESCRIPTION
**Pull request by pamo**
* adds git `pre commit` hook to automatically run linting
* adds git `pre push` hook to automatically run tests
* updates the travis task
* fixes a bunch of eslint errors

Tools introduced
- Prettier: code formatter
- lint-staged: lints files that are about to be commited
- husky: allows you to add git hooks to a repo
- eslint
- eslint config for angular apps

Configured some of the eslint rules for angular as warnings because fixing them in this PR would make it much bigger than what it already is.

### CODE REVIEW

**Comment by pamo** [comment]
Here's what a failed push would look like 
oct-12-2018 21-56-13

**Comment by pamo** [comment]
Tests will be the last bit for me to get working 😅 https://travis-ci.org/pamo/distributed/builds/443521835

**Comment by glauberramos** [comment]
@pamo can you fix the conflicts? I merged older pull requests first

**Comment by pamo** [comment]
Will do

**Comment by pamo** [comment]
🤔 the tests are still broken. Did you do a quick check to see if the app works?

**Comment by pamo** [comment]
@glauberramos np I should add a work in progress label or something so it doesn't happen again.

**Comment by glauberramos** [comment]
Sure, you can add an `WIP -` in front of the PR name. Another suggestion that I have is to create smaller PR's. One just to enable eslint, other to add the pre commit and post commit stuff, another one to fix eslint for controllers, etc...

**Pull request merged**
