### PR TITLE
[ #225 ] Add eslint for es6 linting

### PR DESCRIPTION
**Pull request by Roshanjossey**
I need some help with configurations.

When I try ignoring vendor files in js directory, eslint was ignoring everything. I tried ignoring with each file name, then it was just checking files in vendor directory

### CODE REVIEW

**Comment by pamo** [comment]
@Roshanjossey did you remove jshint? The configurations are probably conflicting each other.

**Comment by pamo** [comment]
We may want to adopt the [airbnb base eslint configuration](https://www.npmjs.com/package/eslint-config-airbnb-base) and/or [angular eslint](https://www.npmjs.com/package/eslint-plugin-angular).

**Comment by Roshanjossey** [comment]
@glauberramos, @pamo, I've added aibnb-base base and angular configurations for eslint.
Now `gulp eslint` command shows around 2200 problems.
How about we add issues to fix those problems and let anybody interested take it up? I'll try to chip away on my end too.

Once that is done, we can add eslint to CI and remove jshint.

**Comment by pamo** [comment]
Try running `eslint --fix .` and checking in any changes. That alone should take care of a few problems.

**Comment by Roshanjossey** [comment]
Awesome. Now we're down to 713 problems

**Comment by pamo** [comment]
I would add a new [npm script](https://github.com/funretro/distributed/blob/master/package.json#L6)
```
 "lint": "npx eslint . && stylelint stylesheets/*.scss",
```
remove the `jshint` script, and change the [CI task](https://github.com/funretro/distributed/blob/master/.travis.yml#L7) to run the new lint script.

**Comment by glauberramos** [comment]
You added a bunch of commits from other PR. I think you can use git `pull --rebase` to avoid those issues.

**Comment by Roshanjossey** [comment]
@glauberramos, @pamo, I'm sorry I messed up this pull request. I've opened #235 for these changes without unnecessary commits. Please review that commit

**Pull request closed without merging**
