### PR TITLE
WIP - 135 improvements to readme

### PR DESCRIPTION
**Pull request by RikTheunis**
- [x]  Line no. 19, 20, 29: Replace 'app' with 'project' to match firebase terminology.
- [x] Line no. 29: Explain where to get the url to be put in firebase service.
- [x] Line no. 51: There is SnapCI with and without link. Remove the one without link
- [x] Line no. 58: Provide link rather than url.

### CODE REVIEW

**Comment by Roshanjossey** [comment]
Awesome @RikTheunis, keep it going.

Quick feedback, it's better to write commit messages in simple present tense.

Rather than `replaced`, `removed`, try to use `replace`, `remove`
Here's an article that may help you to improve commit messages
https://robots.thoughtbot.com/5-useful-tips-for-a-better-commit-message

**Comment by RikTheunis** [comment]
@Roshanjossey I really appreciate the feedback! Tried to apply the suggestions made in the article to my latest commit message. 

Now what is the next step? Should I remove WIP from the title now all the changes are made?

**Comment by Roshanjossey** [comment]
Good job @RikTheunis,

I've added a review comment to a change you made. Could you please look in to that?

Also I don't have write access to this repo. We'll have to wait for @Glauberamos to merge these changes

**Comment by RikTheunis** [comment]
@Roshanjossey I'm sorry, I can't find the review comment you made.

**Comment by Roshanjossey** [comment]
@RikTheunis: Sorry, my bad. I hadn't submitted the review.

**Comment by Roshanjossey** [comment]
@RikTheunis: I'm happy with your changes. We'll wait for @glauberramos to merge these changes.

**Comment by glauberramos** [comment]
Lools nice merging it now. Thanks @RikTheunis

**Comment by RikTheunis** [comment]
Awesome! Thanks @Roshanjossey and @glauberramos for this chance to learn and the useful feedback!

**Comment by Roshanjossey** [comment]
@RikTheunis, would you like to take a stab at issue #110?

https://github.com/funretro/distributed/issues/110

**Pull request merged**
