### PR TITLE
[WIP][#101] Upgrading Firebase and AngularFire

### PR DESCRIPTION
**Pull request by lanesawyer**
Got Firebase and AngularFire upgraded to 3.8.0 and 2.3.0 respectively.

Two unit tests are failing because there is no reference to the global `firebase` variable, and I'm not that familiar with Karma so help would be appreciated on that issue! There are also 6 jshint warnings due to `firebase` not being defined. We might be able to get around this by using AngularFire methods instead of the Firebase ones. EDIT: That worked! Unit tests are still failing though.

Also, all of the config settings are from my personal Firebase account. We'd obviously want to replace those with the ones from the production version.

You'll notice I am pulling Firebase from a CDN instead of putting it in the vender bundle. It's because AngularFire needs Firebase to be initialized, but I couldn't do that in between loading Firebase itself and AngularFire due to the bundling. If you have a way around that issue, I'm all ears!

### CODE REVIEW

**Comment by glauberramos** [comment]
That's awesome! I have been thinking about updating it for a while now, but never got my hands on it. I will check that soon and respond here, thanks.

**Comment by glauberramos** [comment]
We need to add firebase into the vendor bundle, doing that Karma will be able to find firebase variable. What problems you were having when you added to the bundle?

**Comment by lanesawyer** [comment]
Good to know.

The reason I removed it from the bundle and used a CDN is because the Firebase 3.0 initialization code needs to fire before the AngularFire code runs. Since the vender bundle doesn't let us step in and execute code between the Firebase and AngularFire files loading, AngularFire won't initialize correctly.

We could fix it by playing with how all the JS files are bundled and minified. All we need is to put our own JS file between loading Firebase and AngularFire and we're good to go! I can play with it over the next few days.

**Comment by glauberramos** [comment]
I think that's a good idea. Create a file with only the code for firebase initialization and add it between firebase and angularFire on gulpfile.js and also inside karma.conf.js.

Let me know if you have any problem.

**Comment by lanesawyer** [comment]
Go the Firebase initialization code in the right place and everything looks great!

The 4 failing tests seem to have come from the changes in the most recent PR. I'm seeing them fail even when running unit tests from the master branch.

All that's left for my PR is to insert the production Firebase configuration parameters. Feel free to add them yourself, or send them to me and I'll update it.

**Comment by glauberramos** [comment]
Master is fine: take a look here: https://travis-ci.org/funretro/distributed/branches

**Comment by lanesawyer** [comment]
You are 100% correct! It looks like the upgrade on AngularFire is what broke it, and I hadn't done an npm install to get back to the old. I'll go fix it then :)

**Comment by lanesawyer** [comment]
I've mocked out any services that depend on Firebase and that seemed to solve the issue. Let me know what you think about that approach.

Once that's all approved, we just need to drop in your Firebase config settings and we're good to go!

**Comment by glauberramos** [comment]
Cool! I will check that today and let you know what I find.

**Comment by glauberramos** [comment]
I will merge this pull request and change the config myself. Thanks for the nice work on it!

**Pull request merged**
