### PR TITLE
Disable create board button if board name is empty

### LINKED ISSUE #125: bug: create board with empty name

### PR DESCRIPTION
**Pull request by Roshanjossey**
Fixes #125

- Disable create board button based on a function that checks if
  newBoard.name evaluates to false

### CODE REVIEW

**Comment by Roshanjossey** [comment]
@glauberramos, sorry it took so much time to send you this pr. I'm not sure if I get the development workflow correctly.

Here's the error I got from CI
```
/var/snap-ci/repo/node_modules/gulp-sourcemaps/node_modules/strip-bom/index.js:2
module.exports = x => {
                    ^
SyntaxError: Unexpected token >
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/var/snap-ci/repo/node_modules/gulp-sourcemaps/src/init/index.internals.js:7:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/var/snap-ci/repo/node_modules/gulp-sourcemaps/src/init/index.js:10:19)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
Command gulp testci failed with status 8.
Execution took 0m1.2s.
Saving console log for later
```

I'm not sure how to correct this

**Comment by Roshanjossey** [comment]
@glauberramos: I saw that we have the same error in the other PR as well. I googled around a bit about this and this is what I got

http://stackoverflow.com/questions/40220506/gulp-sourcemaps-syntaxerror-unexpected-token

When I try `gulp testci` from my local, it does pass. I'm using node version `5.5.0`
When I looked through CI trace, I learned that were using `node v0.10.37 (npm v1.4.28)`
Should we upgrade node and gulp-sass?

**Comment by glauberramos** [comment]
@Roshanjossey yeah we should update node and gulp-sass. If can add that in the PR as well. 💃

**Comment by Roshanjossey** [comment]
@glauberramos: I prefer to have another pull request for tracking changes in node version. Just because its a big change. It'd be good create another issue and take it from there.

I have a question. I saw a file named `.node-version` with content `5.6.0` and in CI, we're using nvm to set node version. I couldn't find anything that is used by CI. I'm familiar with travis where we use something like `travis.yml` Could you help me out with this?

**Comment by glauberramos** [comment]
I am not sure how to ensure pull requests use the correct version on snap. I will check that.

**Comment by Roshanjossey** [comment]
@glauberraImos, I couldn't understand your last comment. How can I change CI script?

**Comment by glauberramos** [comment]
@Roshanjossey I was saying that I don't know how to change node version on the CI. But I will investigate that.

**Pull request merged**
